// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BevyViewPortComponent: typeof import('./src/app/components/renderer/BevyViewPortComponent.vue')['default']
    copy: typeof import('./src/app/components/renderer/ViewPortComponent copy.vue')['default']
    NotebookWrapper: typeof import('./src/app/components/NotebookWrapper.vue')['default']
    RendererRootViewPortComponent: typeof import('./src/app/components/renderer/RendererRootViewPortComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ViewPortComponent: typeof import('./src/app/components/renderer/ViewPortComponent.vue')['default']
  }
}
