use std::{env, fs, path::PathBuf};

fn hex_to_rgb(hex: &str) -> (u8, u8, u8) {
    let h = hex.trim().trim_start_matches('#');
    let r = u8::from_str_radix(&h[0..2], 16).expect("hex r");
    let g = u8::from_str_radix(&h[2..4], 16).expect("hex g");
    let b = u8::from_str_radix(&h[4..6], 16).expect("hex b");
    (r, g, b)
}

fn get_hex(v: &serde_json::Value, group: &str, shade: &str) -> String {
    v.get(group)
        .and_then(|g| g.get(shade))
        .and_then(|s| s.as_str())
        .unwrap_or_else(|| panic!("missing theme color {}.{}", group, shade))
        .to_string()
}

fn main() {
    // Ensure rebuild when the theme changes.
    println!("cargo:rerun-if-changed=themeColors.json");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let theme_path = manifest_dir.join("themeColors.json");

    let json = fs::read_to_string(&theme_path)
        .unwrap_or_else(|e| panic!("failed to read {:?}: {e}", theme_path));

    let v: serde_json::Value = serde_json::from_str(&json)
        .unwrap_or_else(|e| panic!("failed to parse {:?}: {e}", theme_path));

    // These match the Vue usage:
    // - primary:    themeColors.primary[500]
    // - secondary:  themeColors.secondary[400]
    // - highlight:  themeColors.highlight[300]
    // - tertiary:   themeColors.compliment[300]
    let primary_500 = get_hex(&v, "primary", "500");
    let secondary_400 = get_hex(&v, "secondary", "400");
    let highlight_300 = get_hex(&v, "highlight", "300");
    let compliment_300 = get_hex(&v, "compliment", "300");

    let (p_r, p_g, p_b) = hex_to_rgb(&primary_500);
    let (s_r, s_g, s_b) = hex_to_rgb(&secondary_400);
    let (h_r, h_g, h_b) = hex_to_rgb(&highlight_300);
    let (c_r, c_g, c_b) = hex_to_rgb(&compliment_300);

    let out = format!(
        "// AUTO-GENERATED by build.rs\n\n\
pub const PRIMARY_500: (u8, u8, u8) = ({p_r}, {p_g}, {p_b}); // {primary_500}\n\
pub const SECONDARY_400: (u8, u8, u8) = ({s_r}, {s_g}, {s_b}); // {secondary_400}\n\
pub const HIGHLIGHT_300: (u8, u8, u8) = ({h_r}, {h_g}, {h_b}); // {highlight_300}\n\
pub const COMPLIMENT_300: (u8, u8, u8) = ({c_r}, {c_g}, {c_b}); // {compliment_300}\n"
    );

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    fs::write(out_dir.join("theme_gen.rs"), out).expect("write theme_gen.rs");
}
