import fs from 'node:fs'
import path from 'node:path'

// We parse the TS file directly to avoid needing a TS runtime.
const colorsPath = path.resolve('tailwind/colors.ts')
const src = fs.readFileSync(colorsPath, 'utf8')

function extractHex(key) {
  // Match e.g. `500: '#18946b'` within the specific palette object.
  const re = new RegExp(`${key}\\s*:\\s*'(#(?:[0-9a-fA-F]{6}))'`)
  const m = src.match(re)
  if (!m) throw new Error(`Could not find hex for ${key} in ${colorsPath}`)
  return m[1]
}

// Hardcode the specific references we used in Vue (same as before):
// themeColors.primary[500], secondary[400], highlight[300], compliment[300]
// We locate the palette blocks and then the numbered key inside them.

function findPaletteBlock(paletteName) {
  const start = src.indexOf(`${paletteName}: {`)
  if (start === -1) throw new Error(`Could not find palette ${paletteName}`)
  // naive brace matching
  let i = start
  let depth = 0
  for (; i < src.length; i++) {
    if (src[i] === '{') depth++
    else if (src[i] === '}') {
      depth--
      if (depth === 0) {
        return src.slice(start, i + 1)
      }
    }
  }
  throw new Error(`Unclosed palette block ${paletteName}`)
}

function extractHexFromPalette(paletteName, shade) {
  const block = findPaletteBlock(paletteName)
  const re = new RegExp(`${shade}\\s*:\\s*'(#(?:[0-9a-fA-F]{6}))'`)
  const m = block.match(re)
  if (!m) throw new Error(`Could not find shade ${shade} for ${paletteName}`)
  return m[1]
}

function parseHex(hex) {
  const h = hex.replace('#', '')
  const r = Number.parseInt(h.slice(0, 2), 16)
  const g = Number.parseInt(h.slice(2, 4), 16)
  const b = Number.parseInt(h.slice(4, 6), 16)
  return [r, g, b]
}

function colorToRust(name, hex) {
  const [r, g, b] = parseHex(hex)
  return `pub const ${name.toUpperCase()}: (u8, u8, u8) = (${r}, ${g}, ${b}); // ${hex}`
}

const PRIMARY_500 = extractHexFromPalette('turquoise', 500)
const SECONDARY_400 = extractHexFromPalette('coral', 400)
const HIGHLIGHT_300 = extractHexFromPalette('gold', 300)
const COMPLIMENT_300 = extractHexFromPalette('navy', 300)

const out = `// AUTO-GENERATED by scripts/generate_flock_theme.mjs
// Source: tailwind/colors.ts
//
// Do not edit manually.

${colorToRust('PRIMARY_500', PRIMARY_500)}
${colorToRust('SECONDARY_400', SECONDARY_400)}
${colorToRust('HIGHLIGHT_300', HIGHLIGHT_300)}
${colorToRust('COMPLIMENT_300', COMPLIMENT_300)}
`

process.stdout.write(out)
