import { themeColors } from '../tailwind/colors'

function parseHex(hex: string): [number, number, number] {
  const h = hex.replace('#', '')
  const r = Number.parseInt(h.slice(0, 2), 16)
  const g = Number.parseInt(h.slice(2, 4), 16)
  const b = Number.parseInt(h.slice(4, 6), 16)
  return [r, g, b]
}

function colorToRust(name: string, hex: string) {
  const [r, g, b] = parseHex(hex)
  return `pub const ${name.toUpperCase()}: (u8, u8, u8) = (${r}, ${g}, ${b}); // ${hex}`
}

const out = `// AUTO-GENERATED by scripts/generate_flock_theme.ts
// Source: tailwind/colors.ts
//
// Do not edit manually.

${colorToRust('PRIMARY_500', themeColors.primary[500])}
${colorToRust('SECONDARY_400', themeColors.secondary[400])}
${colorToRust('HIGHLIGHT_300', themeColors.highlight[300])}
${colorToRust('COMPLIMENT_300', themeColors.compliment[300])}
`

process.stdout.write(out)
