// AUTO-GENERATED by scripts/generate_flock_theme.mjs
// Source: tailwind/colors.ts
//
// Do not edit manually.

pub const PRIMARY_500: (u8, u8, u8) = (24, 148, 107); // #18946b
pub const SECONDARY_400: (u8, u8, u8) = (228, 120, 106); // #e4786a
pub const HIGHLIGHT_300: (u8, u8, u8) = (217, 185, 76); // #d9b94c
pub const COMPLIMENT_300: (u8, u8, u8) = (144, 194, 212); // #90c2d4
